---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${PROJECT_ID}
  region: ${AWS_REGION}
  version: "1.21"

availabilityZones: ["${AZ1}", "${AZ2}", "${AZ3}"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 1
  instanceType: t3.small

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}
